# import the necessary components first
import smtplib
import time
import os
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

absolutepath = os.path.abspath(__file__)
fileDirectory = os.path.dirname(absolutepath)
#parentDirectory = os.path.dirname(fileDirectory)
newPath = os.path.join(fileDirectory, 'files')

class EmailSender(object):
    def __init__(self, _initLine, _finishLine, _sleepTime):
        self._initLine = int(_initLine)
        self._finishLine = int(_finishLine)
        self._sleepTime = int(_sleepTime) # Time given in seconds
        self._lastEmailSent = {"emailName": "", "emailLine": 0}
    # Protect this information

    def sendEmail(self): # data40000.csv
        login = "malak.palomino@bvrealty.us" # paste your login generated by Mailtrap
        password = "VREbq8A3vad2" # paste your password generated by Mailtrap # Protect this information
        sender_email = "malak.palomino@bvrealty.us" # Protect this information
        message = MIMEMultipart("alternative")
        message["From"] = sender_email
        with open(f"{newPath}/data40000.csv", 'r') as files:
            lineas = files.readlines()[self._initLine - 1:self._finishLine + 1]
            for index, linea in enumerate(lineas):
                lista = linea.rstrip().split(",")
                if lista[11] != "":
                    self._lastEmailSent['emailName'] = lista[11]
                    self._lastEmailSent['emailLine'] = self._initLine + index
                    #print(lista[0]," ",lista[2],"-",lista[11])
                    message['Subject'] = ""
                    message.replace_header('Subject', f"Blue Vista Realty | {lista[0]}, we are paying you 100% Commission!")
                    f = open(f"{newPath}/index.html", "r")
                    text = f.read()
                    html = text.replace("{lista[0]}", f" {lista[0]}")
                    try:
                        # send your email
                        with smtplib.SMTP("smtp.zoho.com", 587) as server:
                            server.ehlo()
                            server.starttls()
                            server.login(login, password, initial_response_ok = True)
                            server.ehlo()
                            # convert both parts to MIMEText objects and add them to the MIMEMultipart message
                            HTMLPart = MIMEText(html, "html")
                            message.attach(HTMLPart) #Remove or refresh the payload of the attachment
                            print(lista[11])
                            server.sendmail(sender_email, lista[11], message.as_string())
                            message.set_payload(None)
                            print(f"Email sent to: {lista[11]}")
                            server.close()
                    # Using exceptions to avoid connection loss
                    except smtplib.SMTPRecipientsRefused: continue
                    except smtplib.SMTPDataError as err:
                        return {"sucess": False, "errorType": str(smtplib.SMTPDataError), 
                        "errDescription": err, "lastEmail": self._lastEmailSent['emailName'], 
                        "emailLine": self._lastEmailSent['emailLine']}
                time.sleep(self._sleepTime)
        return {"success": True, "lastEmail": self._lastEmailSent}