# import the necessary components first
import smtplib
import time
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

class EmaiSender(object):
    def __init__(self, _initLine, _finishLine, _sleepTime):
        self._initLine = int(_initLine)
        self._finishLine = int(_finishLine)
        self._sleepTime = int(_sleepTime) # Time given in seconds
    # Protect this information
    @classmethod
    def sendEmail(self, _destinationFiles): # data40000.csv
        login = "malak.palomino@bvrealty.us" # paste your login generated by Mailtrap
        password = "VREbq8A3vad2" # paste your password generated by Mailtrap # Protect this information
        sender_email = "malak.palomino@bvrealty.us" # Protect this information
        message = MIMEMultipart("alternative")
        message["From"] = sender_email
        with open(_destinationFiles, 'r') as files:
            lineas = files.readlines()[self._initLine - 1:self._finishLine + 1]
            for linea in lineas:
                linea = linea.rstrip()
                lista = linea.split(",")
                if lista[11] != "":
                    #print(lista[0]," ",lista[2],"-",lista[11])
                    message['Subject'] = ""
                    message.replace_header('Subject', f"Blue Vista Realty | {lista[0]}, we are paying you 100% Commission!")
                    f = open("index.html", "r")
                    text = f.read()
                    html = text.replace("{lista[0]}", f" {lista[0]}") 

                    try:
                        # send your email
                        with smtplib.SMTP("smtp.zoho.com", 587) as server:
                            server.ehlo()
                            server.starttls()
                            server.login(login, password, initial_response_ok = True)
                            server.ehlo()
                            # convert both parts to MIMEText objects and add them to the MIMEMultipart message
                            HTMLPart = MIMEText(html, "html") 
                            message.attach(HTMLPart) #Remove or refresh the payload of the attachment
                            print(lista[11])
                            server.sendmail(sender_email, lista[11], message.as_string())
                            message.set_payload(None)
                            print(f"Email sent to: {lista[11]}")
                            server.close()
                    # Using exceptions to avoid connection loss
                    except smtplib.SMTPRecipientsRefused: continue
                    except smtplib.SMTPDataError: 
                        return {"Error": smtplib.SMTPDataError}
                time.sleep(self._sleepTime)
        return {"success": "All emails sent!", "last_line": lista[11]}